### ISSUE TITLE
Adding more concise matchers support

### ISSUE THREAD

**Issue by plouc** [ekino/veggies#16]
For now we have a pretty verbose way to express assertions to be made on complex objects, like this:

```gherkin
And json response should match
    | field | matcher | value     |
    | id    | contain | 123       |
    | name  | equal   | John      |
    | corp  | match   | ^(.+)ing$ |
```  

I think we could provide the ability to use shorter notation, like this:

```gherkin
And json response should match
    | id *= 123         |
    | name = John       |
    | corp ~= ^(.+)ing$ |
```  

Here is my proposal to do so (heavily inspired by [CSS attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)):

| matcher          | operator |
|------------------|----------|
| **equals**       |  `=`     |
| **match regexp** | `~=`     |
| **contains**     | `*=`     |
| **ends with**    | `$=`     |
| **starts with**  | `^=`     |

**Comment by plouc** [comment]
ping @bnadim, @aticus7886, what do you think?

**Comment by bnadim** [comment]
why not it's easier to red :)
