### ISSUE TITLE
Upgrade to cucumber 7

### ISSUE THREAD

**Issue by fthouraud** [ekino/veggies#57]
Hi there 👋 

The new cucumber version is here: [7.0.0](https://www.npmjs.com/package/@cucumber/cucumber).

Because the cucumber package has also been renamed (it is now `@cucumber/cucumber`), maybe we should consider releasing a major version.

What do you think?

I'll be glad to help.

**Comment by Crow-EH** [comment]
Indeed, the simple fact that it changes the peerDependency is a breaking change.
