### ISSUE TITLE
Snapshot generation should be the default on CI environment

### ISSUE THREAD

**Issue by fthouraud** [ekino/veggies#59]
Hello 👋 

## Context

The snapshot is a painless way to test the output of an API but it has to be created, checked, and committed by the developer who writes the code.

## Current behavior

If the snapshot does not exist for the current test, it is automatically created. Otherwise, when the update flag has been passed to the command line the snapshot is updated.

## Proposed behavior

Considering that it's the developer's job to create, check, and commit the snapshot I think that its creation shouldn't be automated in a CI environment.
It's also the default behavior on Jest since its version 20 as answered in the [Q&A section](https://jestjs.io/docs/snapshot-testing):

> Are snapshots written automatically on Continuous Integration (CI) systems?
> No, as of Jest 20, snapshots in Jest are not automatically written when Jest is run in a CI system without explicitly passing --updateSnapshot. It is expected that all snapshots are part of the code that is run on CI and since new snapshots automatically pass, they should not pass a test run on a CI system. It is recommended to always commit all snapshots and to keep them in version control.

## Suggested implementations

I can think of two options here.

### Automated check for CI environment

First thing first, we need to know if we're in a CI environment. For this purpose, we could make use of the `ci-info` [package](https://www.npmjs.com/package/ci-info) which supports a large number of vendors.

Then, we simply change the condition on creating a new snapshot: it does not exist and it is not running from the CI.

Obviously, this is a breaking change.

### Dedicated flag

A simpler option would be to add a `--preventSnapshotCreation` flag which would prevent the snapshot creation.

It is explicit and does not break the current behavior.

We could also opt for a broader flag like `--ci` which could be used for other future restrictions in a CI environment.

I'll be happy to have your feeling about this.

**Comment by Crow-EH** [comment]
The flag would be a more flexible and agnostic way of doing it : This behavior may be needed elsewhere than in CI.

It should also be configurable through the snapshot extension's options like `updateSnapshots`
