### ISSUE TITLE
Update Node.js versions

### ISSUE THREAD

**Issue by fthouraud** [ekino/veggies#62]
Hi 👋 

## Context

Node 10 support has ended a few months back.
Besides, Node 16 is coming up in a few months too ([26th of October this year](https://nodejs.org/fr/about/releases/)).

## Proposal

We should take the following actions:

- Support Node 12 and up
- Remove tests on Node 10
- Add tests on Node 16

**Comment by Crow-EH** [comment]
Required before merging https://github.com/ekino/veggies/pull/60
