### ISSUE TITLE
Cucumber does not allow custom options anymore

### ISSUE THREAD

**Issue by fthouraud** [ekino/veggies#67]
Hi there 👋 

Since Cucumber 7, it seems that custom command-line options are not allowed anymore (cf. cucumber/cucumber-js#1666 & cucumber/cucumber-js#1474) and that's a shame.

So we now have a problem, because all our options now produce an error (except `--tags`):
`error: unknown option '-u'`

We have to think of another way to handle custom options 😬 

Edit 1: add a reference to the original issue on cucumber-js

**Comment by Crow-EH** [comment]
We should also tests that they are working in our CI. 😅

**Comment by Crow-EH** [comment]
@fthouraud the issue you linked has been flagged as a duplicate, please link to https://github.com/cucumber/cucumber-js/issues/1474 instead

**Comment by Crow-EH** [comment]
It seems that the only easy workarround is to use env variables

**Comment by fthouraud** [comment]
> @fthouraud the issue you linked has been flagged as a duplicate, please link to [cucumber/cucumber-js#1474](https://github.com/cucumber/cucumber-js/issues/1474) instead

I'm not sure it helps because none of the comments reveals the new official way to provide custom options: [`--world-parameters`](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/world.md#world-parameters).
