### ISSUE TITLE
Automating the release process

### ISSUE THREAD

**Issue by fthouraud** [ekino/veggies#70]
Hi 👋 

Currently, the release process is manual and cumbersome. We could extend our use of the GH Actions to automate some of the steps if not all.

We have an example on [ekino/smuggler](https://github.com/ekino/smuggler) of what could be done. Story short:
- a manually triggered workflow creates a PR with version bump and changelogs update,
- an automated workflow on tags to package, upload to NPM, and create a release.

Maybe the changelog is nice to have but automating the release process is mandatory.

Of course, we can discuss here what we could do better if anyone has an idea.

**Comment by tienduy-nguyen** [comment]
This issue could be closed.
