### ISSUE TITLE
Add yaml linting

### ISSUE THREAD

**Issue by Crow-EH** [ekino/veggies#83]
We should add a yaml linter, on localhost and CI, to reduce noise in pull requests.

**Comment by fthouraud** [comment]
You can have a look at [gherking/gherkin-io](https://github.com/gherking/gherkin-io) which is a simple parser including formatting feature.

**Comment by Crow-EH** [comment]
We can do it with prettier directly (plus we're talking about yaml, not gherkin 😄 )

**Comment by fthouraud** [comment]
> We can do it with prettier directly (plus we're talking about yaml, not gherkin 😄 )

Well, I've missed the topic I guess. 😅

And you're right, Prettier should do the job 👍
